### ISSUE TITLE
upload to s3 bucket path without versioning and overwriting existing file

### ISSUE THREAD

**Issue by HoffiMuc** [concourse/s3-resource#140]
Hi,

I'd like to have the ability to upload to s3 bucket path/filename WITHOUT versioning the file.

So if the file already exists it is just overwritten (on a bucket _without_ versioning enabled)

**Comment by vito** [comment]
This won't be done because it's counter to the very notion of what makes this a resource type. :slightly_smiling_face: 

More context here: https://github.com/concourse/s3-resource/issues/133

If you just need to upload something to S3 and don't care at all about versioning, I would suggest just doing it in a task for now.

Thanks!
